### ISSUE TITLE
User Documentation: Content Task List

### ISSUE THREAD

**Issue by JoelMarcey** [hhvm/user-documentation#1]
This list contains the actual user-content tasks that need to be completed. Choose a topic, comment on this issue with the topic you will be working on, write great content, get it peer-reviewed and check the box off when completed. 

**IMPORTANT**: Please follow the [contribution guidelines](https://github.com/hhvm/user-documentation/blob/master/CONTRIBUTING.md) when adding or modifying content.

**NOTE**: Feel free to add to or modify this list as appropriate as we move along in our efforts here. This is just the initial skeleton guide of how we should approach the docs. It can change, of course. 

**NOTE**: All the Hack markdown `.md` placeholders are in `hack/<##-topic>` and the HHVM placeholders are in `hhvm/<##-topic>`, where `##` represents a table of contents placeholder suitable for documentation generation tooling. Obviously feel free to add or change any of the placeholders to better suit your documentation efforts.

**NOTE**: @fredemmott is creating the infra to tie all of the content documentation in our markdown files with the API documentation.

- [x] [Hack Quickstart](https://github.com/hhvm/user-documentation/tree/master/guides/hack/quickstart.md) (**@JoelMarcey**)
 - [x] [Types](https://github.com/hhvm/user-documentation/tree/master/guides/hack/01-types) (**@JoelMarcey**)
 - [x] [Generics](https://github.com/hhvm/user-documentation/tree/master/guides/hack/02-generics) (**@RexJaeschke**, **@int3**)
 - [x] [Async](https://github.com/hhvm/user-documentation/tree/master/guides/hack/03-async) (**@JoelMarcey**)
 - [x] [Collections](https://github.com/hhvm/user-documentation/tree/master/guides/hack/04-collections) (**@JoelMarcey**)
 - [x] [XHP](https://github.com/hhvm/user-documentation/tree/master/guides/hack/05-xhp) (**@JoelMarcey**)
 - [x] [Type Aliases](https://github.com/hhvm/user-documentation/tree/master/guides/hack/06-type-aliases) (**@RexJaeschke**)
 - [x] [Lambdas](https://github.com/hhvm/user-documentation/tree/master/guides/hack/07-lambdas) (**@SiebelsTim**, **@JoelMarcey**)
 - [x] [Shapes](https://github.com/hhvm/user-documentation/tree/master/guides/hack/08-shapes) (**@RexJaeschke**)
 - [x] [Type Constants](https://github.com/hhvm/user-documentation/tree/master/guides/hack/09-type-constants) (**@JoelMarcey**)
 - [x] [Operators](https:/github.com/hhvm/user-documentation/tree/master/guides/hack/10-operators) (**@JoelMarcey**)
 - [x] [Attributes](https://github.com/hhvm/user-documentation/tree/master/guides/hack/11-attributes) (**@JoelMarcey**)
 - [x] [Enums](https://github.com/hhvm/user-documentation/tree/master/guides/hack/12-enums) (**@JoelMarcey**)
 - [x] [Callables](https://github.com/hhvm/user-documentation/tree/master/guides/hack/13-callables) (**@JoelMarcey**)
 - [x] [Other Features](https://github.com/hhvm/user-documentation/tree/master/guides/hack/14-other-features) (**@JoelMarcey**)
 - [x] [Unsupported Features](https://github.com/hhvm/user-documentation/tree/master/guides/hack/15-unsupported) (**@JoelMarcey**)
 - [x] [Typechecker](https://github.com/hhvm/user-documentation/tree/master/guides/hack/16-typechecker) (**@JoelMarcey**)
 - [x] [Tools](https://github.com/hhvm/user-documentation/tree/master/guides/hack/17-tools)  (**@JoelMarcey**)
 - [x] [FAQ](https://github.com/hhvm/user-documentation/tree/master/guides/hack/98-FAQ) (**@JoelMarcey**)
 - [ ] [API Examples](https://github.com/hhvm/user-documentation/tree/master/guides/hack/99-api-examples)
    - [x] [AsyncMySQL](https://github.com/hhvm/user-documentation/tree/master/guides/hack/99-api-examples/async-mysql-examples) (**@JoelMarcey**)
    - [ ] [Collections](https://github.com/hhvm/user-documentation/tree/master/guides/hack/99-api-examples/collections-examples) (**@JoelMarcey**)
    - [ ] [Asio](https://github.com/hhvm/user-documentation/tree/master/guides/hack/99-api-examples/asio-examples) (**@JoelMarcey**)
    - [x] [McRouter](https://github.com/hhvm/user-documentation/tree/master/guides/hack/99-api-examples/mcrouter-examples) (**@JoelMarcey**)
- [x] [HHVM Quickstart](https://github.com/hhvm/user-documentation/tree/master/guides/hhvm/quickstart.md) (**@JoelMarcey**)
 - [x] [Installation](https://github.com/hhvm/user-documentation/blob/master/guides/hhvm/01-installation) (**@JoelMarcey**)
 - [x] [Configuration](https://github.com/hhvm/user-documentation/tree/master/guides/hhvm/02-configuration) (**@JoelMarcey**)
   - [x] [INI Settings](https://github.com/hhvm/user-documentation/blob/master/guides/hhvm/02-configuration/02-ini-settings.md) (**@JoelMarcey**)
 - [x] [Deployment](https://github.com/hhvm/user-documentation/blob/master/guides/hhvm/03-deployment) (**@JoelMarcey**)
 - [x] [Using Extensions](https://github.com/hhvm/user-documentation/blob/master/guides/hhvm/04-extensions) (**@JoelMarcey**)
 - [x] [Inconsistencies to PHP](https://github.com/hhvm/user-documentation/blob/master/guides/hhvm/05-inconsistencies) (**@JoelMarcey**)
 - [x] [FAQ](https://github.com/hhvm/user-documentation/tree/master/guides/hhvm/98-FAQ) (**@JoelMarcey**)
- [x] Other
  - [x] Update Test Runner to support running the typechecker and `.typechecker.expect[f]` and `.hhvm.expect[f]` (**@JoelMarcey**)
  - [x] Document Collections Interfaces via docblocks in `hphp/hack/hhi/collections/interfaces.hhi`

**Comment by JoelMarcey** [comment]
Re: HHVM configuration -- I marked that as checked off because I believe we have enough in there not to block initial launch. However, work needs to be done to document the ini settings better (hopefully within code) and we can add more configuration option usage examples as well.

**Comment by JoelMarcey** [comment]
Re: HHVM FAQ - I marked that as checked off because there are a bit of questions in the FAQ now; we understand that is a living document and can probably also be a bit more dynamic with popular being able to be marked as such and bubbling to the top (or maybe part of the front page of the docs or something).

**Comment by JoelMarcey** [comment]
The XHP section is finished, but there is what I think is a bug in the context example in the guidelines section. 

See comment in this commit: https://github.com/hhvm/user-documentation/commit/a3cccd738f20960a0985026e5aca4d350b38559d

@oyamauchi @fredemmott

**Comment by JoelMarcey** [comment]
I think we have done //really// well on getting the initial docs out into a beta form \o/

I am going to close this issue and make two new issues for adding examples for collections and asio separately.
